query GenePageQuery($geneId: String!) {
  geneInfo(geneId: $geneId) {
    id
    symbol
    chromosome
    start
    end
    bioType
  }
  studiesAndLeadVariantsForGene(geneId: $geneId) {
    indexVariant {
      rsId
      id
    }
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pmid
      nInitial
      nReplication
      nCases
    }
    pval
    oddsRatio
    oddsRatioCILower
    oddsRatioCIUpper
    beta
    betaCILower
    betaCIUpper
    direction
  }
  colocalisationsForGene(geneId: $geneId) {
    leftVariant {
      id
      rsId
    }
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pmid
    }
    qtlStudyId
    phenotypeId
    tissue {
      id
      name
    }
    h3
    h4
    log2h4h3
  }
}
