query GenePageQuery($geneId: String!) {
  geneInfo(geneId: $geneId) {
    id
    symbol
    chromosome
    start
    end
    bioType
  }
  studiesAndLeadVariantsForGeneByL2G(geneId: $geneId) {
    pval
    yProbaModel
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pmid
      nInitial
      nReplication
      hasSumstats
    }
    variant {
      rsId
      id
    }
    odds{
      oddsCI
      oddsCILower
      oddsCIUpper
    }
    beta{
      betaCI
      betaCILower
      betaCIUpper
      direction
    }
  }
  colocalisationsForGene(geneId: $geneId) {
    leftVariant {
      id
      rsId
    }
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pmid
      hasSumstats
    }
    qtlStudyId
    phenotypeId
    tissue {
      id
      name
    }
    h3
    h4
    log2h4h3
  }
}
