query GenePageQuery($geneId: String!) {
  search(queryString: $geneId) {
    genes {
      id
      symbol
      chromosome
      start
      end
      bioType
    }
  }
  studiesForGene(geneId: $geneId) {
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pmid
      nInitial
      nReplication
      nCases
    }
  }
}
