query LocusTraitPageQuery($studyId: String!, $indexVariantId: String!) {
  # reuse from elsewhere
  studyInfo(studyId: $studyId) {
    studyId
    traitReported
    pubAuthor
    pubDate
    pubJournal
    pmid
    nInitial
    nReplication
    nCases
  }
  # reuse from elsewhere
  variantInfo(variantId: $indexVariantId) {
    rsId
    nearestGene {
      id
      symbol
    }
    nearestCodingGene {
      id
      symbol
    }
  }
  # reuse from elsewhere
  # get genes within 1MB (?) away from the index variant
  genes(indexVariantId: $indexVariantId) {
    id
    symbol
    tss
    start
    end
    exons
  }
  # new - uses coloc results table (#286)
  # api could return combined as in db table, or split into gwas vs qtl
  colocalisationSummary(studyId: $studyId, indexVariantId: $indexVariantId) {
    associations {
      signalType # (!) eqtl | pqtl | gwas
      studyId # either studyId or phenotypeId+biofeature will be specified
      phenotypeId # ensgId? - ideally rename
      biofeature # tissue - ideally rename (maybe object with id+name?)
      indexVariant {
        id
        rsId
      }
      posteriorProbabilityH4 # other stats available in table - h3, logH4H3
    }
  }
}
