query PheWASQuery($variantId: String!) {
  pheWAS(variantId: $variantId) {
    totalGWASStudies
    associations {
      study {
        studyId
        traitReported
        traitCategory
        pmid
        pubDate
        pubAuthor
        source
      }
      pval
      beta
      oddsRatio
      nTotal
      nCases
      eaf
      se
    }
  }
}
