query PheWASQuery($variantId: String!) {
  pheWAS(variantId: $variantId) {
    associations {
      study {
        studyId
        traitReported
        traitCategory
      }
      pval
      beta
      oddsRatio
      nTotal
      nCases
      eaf
      se
    }
  }
}
