query StudyPageQuery($studyId: String!) {
  studyInfo(studyId: $studyId) {
    studyId
    traitReported
    pubAuthor
    pubDate
    pubJournal
    pmid
    nInitial
    nReplication
    nCases
    hasSumsStats
  }
  manhattan(studyId: $studyId) {
    associations {
      variant {
        id
        rsId
        chromosome
        position
      }
      pval
      credibleSetSize
      ldSetSize
      oddsRatio
      oddsRatioCILower
      oddsRatioCIUpper
      beta
      betaCILower
      betaCIUpper
      direction
      bestGenes {
        score
        gene {
          id
          symbol
        }
      }
      bestColocGenes {
        score
        gene {
          id
          symbol
        }
      }
    }
  }
}
