query StudyLocusPageQuery(
  $studyId: String!
  $variantId: String!
  $chromosome: String!
  $start: Long!
  $end: Long!
) {
  variantInfo(variantId: $variantId) {
    # id # TODO: investigate; bizarrely, if id is requested, rsId is null in the cache (but valid in the response)
    rsId
    chromosome
    position
    refAllele
    altAllele
    chromosomeB37
    positionB37
  }
  studyInfo(studyId: $studyId) {
    studyId
    traitReported
    pubAuthor
    pubDate
    pubJournal
    pmid
  }
  studyLocus2GeneTable(studyId: $studyId, variantId: $variantId) {
    rows {
      gene {
        symbol
        id
      }
      yProbaModel
      yProbaDistance
      # yProbaInterlocus
      yProbaInteraction
      yProbaMolecularQTL
      yProbaPathogenicity
      hasColoc
      distanceToLocus
    }
  }
  gwasColocalisation(studyId: $studyId, variantId: $variantId) {
    indexVariant {
      id
      rsId
      chromosome
      position
      refAllele
      altAllele
    }
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pubJournal
      pmid
      hasSumstats
    }
    beta
    h3
    h4
    log2h4h3
  }
  qtlColocalisation(studyId: $studyId, variantId: $variantId) {
    indexVariant {
      id
      rsId
      chromosome
      position
      refAllele
      altAllele
    }
    gene {
      id
      symbol
      chromosome
      start
      end
      bioType
    }
    phenotypeId
    tissue {
      id
      name
    }
    qtlStudyName
    beta
    h3
    h4
    log2h4h3
  }
  #   gwasColocalisationForRegion(
  #     chromosome: $chromosome
  #     start: $start
  #     end: $end
  #   ) {
  #     leftVariant {
  #       id
  #       rsId
  #     }
  #     leftStudy {
  #       studyId
  #       traitReported
  #       pubAuthor
  #       pubDate
  #     }
  #     rightVariant {
  #       id
  #       rsId
  #     }
  #     rightStudy {
  #       studyId
  #       traitReported
  #       pubAuthor
  #       pubDate
  #     }
  #     h3
  #     h4
  #     log2h4h3
  #   }

  pageCredibleSet: gwasCredibleSet(studyId: $studyId, variantId: $variantId) {
    tagVariant {
      id
      rsId
      position
    }
    pval
    se
    beta
    postProb
    MultisignalMethod
    logABF
    is95
    is99
  }

  pageSummary: studyAndLeadVariantInfo(
    studyId: $studyId
    variantId: $variantId
  ) {
    indexVariant {
      rsId
    }
    study {
      traitReported
    }
    pvalMantissa
    pvalExponent
    oddsRatio
    oddsRatioCILower
    oddsRatioCIUpper
    beta
    direction
    betaCILower
    betaCIUpper
  }

  genes(chromosome: $chromosome, start: $start, end: $end) {
    id
    symbol
    tss
    start
    end
    exons
  }
}
