query TopOverlappedStudiesQuery($studyId: String!, $studyIds: [String!]!) {
  studyInfo(studyId: $studyId) {
    studyId
    traitReported
    pubAuthor
    pubDate
    pubJournal
    pmid
    nInitial
    nReplication
    nCases
  }
  manhattan(studyId: $studyId) {
    associations {
      variant {
        id
        rsId
        chromosome
        position
      }
      pval
      credibleSetSize
      ldSetSize
      bestGenes {
        score
        gene {
          id
          symbol
        }
      }
    }
  }
  topOverlappedStudies(studyId: $studyId) {
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pubJournal
      pmid
      nInitial
      nReplication
      nCases
    }
    topStudiesByLociOverlap {
      study {
        studyId
        traitReported
        pubAuthor
        pubDate
        pubJournal
        pmid
        nInitial
        nReplication
        nCases
      }
      numOverlapLoci
    }
  }
  overlapInfoForStudy(studyId: $studyId, studyIds: $studyIds) {
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pubJournal
      pmid
      nInitial
      nReplication
      nCases
    }
    overlappedVariantsForStudies {
      study {
        studyId
        traitReported
        pubAuthor
        pubDate
        pubJournal
        pmid
        nInitial
        nReplication
        nCases
      }
      overlaps {
        variantIdA
        variantIdB
        overlapAB
        distinctA
        distinctB
      }
    }
    variantIntersectionSet
  }
}
