query VariantPageQuery($variantId: String!) {
  variantInfo(variantId: $variantId) {
    rsId
    chromosome
    position
    idB37
    chromosomeB37
    positionB37
    refAllele
    altAllele
    nearestGene {
      id
      symbol
    }
    nearestGeneDistance
    nearestCodingGene {
      id
      symbol
    }
    nearestCodingGeneDistance
    mostSevereConsequence
    caddRaw
    caddPhred
    gnomadAFR
    gnomadAMR
    gnomadASJ
    gnomadEAS
    gnomadFIN
    gnomadNFE
    gnomadNFEEST
    gnomadNFENWE
    gnomadNFESEU
    gnomadOTH
  }
  genesForVariantSchema {
    qtls {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
    intervals {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
    functionalPredictions {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
    distances {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
  }
  genesForVariant(variantId: $variantId) {
    gene {
      id
      symbol
    }
    overallScore
    qtls {
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        quantile
        beta
        pval
      }
    }
    intervals {
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        quantile
        score
      }
    }
    functionalPredictions {
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        maxEffectLabel
        maxEffectScore
      }
    }
    distances {
      typeId
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        distance
        score
        quantile
      }
    }
  }
  indexVariantsAndStudiesForTagVariant(variantId: $variantId) {
    associations {
      indexVariant {
        id
        rsId
      }
      study {
        studyId
        traitReported
        pmid
        pubDate
        pubAuthor
        hasSumstats
      }
      pval
      nTotal
      overallR2
      posteriorProbability
      oddsRatio
      oddsRatioCILower
      oddsRatioCIUpper
      beta
      betaCILower
      betaCIUpper
      direction
    }
  }
  tagVariantsAndStudiesForIndexVariant(variantId: $variantId) {
    associations {
      tagVariant {
        id
        rsId
      }
      study {
        studyId
        traitReported
        pmid
        pubDate
        pubAuthor
      }
      pval
      nTotal
      overallR2
      posteriorProbability
    }
  }
}
