query StudySummaryQuery($studyId: String!) {
  studyInfo(studyId: $studyId) {
    studyId
    traitReported
    pubAuthor
    pubDate
    pubJournal
    pmid
    nInitial
    nReplication
    nCases
    hasSumstats
  }
}
